package phenan.prj

object CommonNames {
  val dslClassName            = "proteaj/impl/DSL"
  val priorityClassName       = "proteaj/impl/Priority"
  val classSigClassName       = "proteaj/impl/ClassSig"
  val methodSigClassName      = "proteaj/impl/MethodSig"
  val fieldSigClassName       = "proteaj/impl/FieldSig"
  val operatorClassName       = "proteaj/impl/Operator"
  val metaParamClassName      = "proteaj/impl/MetaParameter"
  val opElemClassName         = "proteaj/impl/OpElem"
  val opLevelClassName        = "proteaj/impl/OpLevel"
  val opElemTypeClassName     = "proteaj/impl/OpElemType"
  val constraintClassName     = "proteaj/impl/Constraint"
  val pureClassName           = "proteaj/impl/Pure"
  val finalizerClassName      = "proteaj/impl/Finalizer"
  val typeClassName           = "proteaj/lang/Type"
  val pairClassName           = "proteaj/lang/Pair"
  val predefOperatorsName     = "proteaj/lang/PredefOperators"
  val arraysUtilClassName     = "proteaj/internal/Arrays"
  val activatedCtxClassName   = "proteaj/internal/ActivatedContexts"
  val supplierRunnerClassName = "proteaj/internal/SupplierRunner"
  val boxedBooleanClassName   = "java/lang/Boolean"
  val boxedByteClassName      = "java/lang/Byte"
  val boxedCharClassName      = "java/lang/Character"
  val boxedShortClassName     = "java/lang/Short"
  val boxedIntClassName       = "java/lang/Integer"
  val boxedLongClassName      = "java/lang/Long"
  val boxedFloatClassName     = "java/lang/Float"
  val boxedDoubleClassName    = "java/lang/Double"
  val boxedVoidClassName      = "java/lang/Void"
  val classClassName          = "java/lang/Class"
  val enumClassName           = "java/lang/Enum"
  val iterableClassName       = "java/lang/Iterable"
  val objectClassName         = "java/lang/Object"
  val stringClassName         = "java/lang/String"
  val errorClassName          = "java/lang/Error"
  val runtimeExceptionName    = "java/lang/RuntimeException"
  val functionClassName       = "java/util/function/Function"
  val consumerClassName       = "java/util/function/Consumer"
  val supplierClassName       = "java/util/function/Supplier"
  val superClassesOfArray     = List(objectClassName, "java/io/Serializable", "java/lang/Cloneable")
  val constructorName         = "<init>"
  val classInitializerName    = "<clinit>"
  val instanceInitializerName = ""
}
