package phenan.prj

object CommonNames {
  val dslClassName            = "proteaj/lang/DSL"
  val priorityClassName       = "proteaj/lang/Priority"
  val classSigClassName       = "proteaj/lang/ClassSig"
  val methodSigClassName      = "proteaj/lang/MethodSig"
  val fieldSigClassName       = "proteaj/lang/FieldSig"
  val operatorClassName       = "proteaj/lang/Operator"
  val metaParamClassName      = "proteaj/lang/MetaParameter"
  val opElemClassName         = "proteaj/lang/OpElem"
  val opLevelClassName        = "proteaj/lang/OpLevel"
  val opElemTypeClassName     = "proteaj/lang/OpElemType"
  val constraintClassName     = "proteaj/lang/Constraint"
  val contextClassName        = "proteaj/lang/Context"
  val pureClassName           = "proteaj/lang/Pure"
  val finalizerClassName      = "proteaj/lang/Finalizer"
  val typeClassName           = "proteaj/lang/Type"
  val classClassName          = "java/lang/Class"
  val enumClassName           = "java/lang/Enum"
  val iterableClassName       = "java/lang/Iterable"
  val objectClassName         = "java/lang/Object"
  val stringClassName         = "java/lang/String"
  val errorClassName          = "java/lang/Error"
  val runtimeExceptionName    = "java/lang/RuntimeException"
  val functionClassName       = "java/util/function/Function"
  val superClassesOfArray     = List(objectClassName, "java/io/Serializable", "java/lang/Cloneable")
  val constructorName         = "<init>"
  val classInitializerName    = "<clinit>"
  val instanceInitializerName = ""
}
